version: '3'
services:
  db:
    image: postgres:latest
    container_name: api_only-db
    environment:
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:6.0.10-alpine
    container_name: api_only-redis
    command: redis-server --appendonly yes # https://redis.io/topics/persistence
    ports:
      - 6379:6379
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/myapp'
    depends_on:
      - redis
    environment:
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
  api:
    build: .
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - db
      - redis